#############################################################################
# Makefile for building: veranda_satelite_parser
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Apr 8 13:44:19 2015
# Project:  veranda_satelite_parser.pro
# Template: app
# Command: /home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++-64 -o Makefile veranda_satelite_parser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
#CFLAGS        = -m64
#CXXFLAGS      = -m64
INCPATH       = -I../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++-64 -I. -I../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtNetwork -I../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtSql -I../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/include -Icompile
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtSql -L/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = compile/

####### Files

SOURCES       = main.cpp \
		util/util_skyw.cpp \
		view/skywavenetwork.cpp \
		model/get_db.cpp \
		controller/worker.cpp \
		model/save_db.cpp \
		model/init_mysql.cpp compile/moc_util_skyw.cpp \
		compile/moc_skywavenetwork.cpp \
		compile/moc_worker.cpp
OBJECTS       = compile/main.o \
		compile/util_skyw.o \
		compile/skywavenetwork.o \
		compile/get_db.o \
		compile/worker.o \
		compile/save_db.o \
		compile/init_mysql.o \
		compile/moc_util_skyw.o \
		compile/moc_skywavenetwork.o \
		compile/moc_worker.o
DIST          = ../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		veranda_satelite_parser.pro
QMAKE_TARGET  = veranda_satelite_parser
DESTDIR       = 
TARGET        = veranda_satelite_parser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: veranda_satelite_parser.pro  ../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++-64/qmake.conf ../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtSql.prl \
		/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl \
		/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++-64 -o Makefile veranda_satelite_parser.pro
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtSql.prl:
/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../application/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++-64 -o Makefile veranda_satelite_parser.pro

dist: 
	@$(CHK_DIR_EXISTS) compile/veranda_satelite_parser1.0.0 || $(MKDIR) compile/veranda_satelite_parser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) compile/veranda_satelite_parser1.0.0/ && $(COPY_FILE) --parents util/util_skyw.h view/skywavenetwork.h model/get_db.h controller/worker.h model/save_db.h model/init_mysql.h compile/veranda_satelite_parser1.0.0/ && $(COPY_FILE) --parents main.cpp util/util_skyw.cpp view/skywavenetwork.cpp model/get_db.cpp controller/worker.cpp model/save_db.cpp model/init_mysql.cpp compile/veranda_satelite_parser1.0.0/ && (cd `dirname compile/veranda_satelite_parser1.0.0` && $(TAR) veranda_satelite_parser1.0.0.tar veranda_satelite_parser1.0.0 && $(COMPRESS) veranda_satelite_parser1.0.0.tar) && $(MOVE) `dirname compile/veranda_satelite_parser1.0.0`/veranda_satelite_parser1.0.0.tar.gz . && $(DEL_FILE) -r compile/veranda_satelite_parser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: compile/moc_util_skyw.cpp compile/moc_skywavenetwork.cpp compile/moc_worker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) compile/moc_util_skyw.cpp compile/moc_skywavenetwork.cpp compile/moc_worker.cpp
compile/moc_util_skyw.cpp: util/util_skyw.h
	/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) util/util_skyw.h -o compile/moc_util_skyw.cpp

compile/moc_skywavenetwork.cpp: view/skywavenetwork.h
	/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) view/skywavenetwork.h -o compile/moc_skywavenetwork.cpp

compile/moc_worker.cpp: util/util_skyw.h \
		view/skywavenetwork.h \
		model/get_db.h \
		controller/worker.h
	/home/rifqi/work/application/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) controller/worker.h -o compile/moc_worker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

compile/main.o: main.cpp controller/worker.h \
		util/util_skyw.h \
		view/skywavenetwork.h \
		model/get_db.h \
		model/init_mysql.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/main.o main.cpp

compile/util_skyw.o: util/util_skyw.cpp util/util_skyw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/util_skyw.o util/util_skyw.cpp

compile/skywavenetwork.o: view/skywavenetwork.cpp view/skywavenetwork.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/skywavenetwork.o view/skywavenetwork.cpp

compile/get_db.o: model/get_db.cpp model/get_db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/get_db.o model/get_db.cpp

compile/worker.o: controller/worker.cpp controller/worker.h \
		util/util_skyw.h \
		view/skywavenetwork.h \
		model/get_db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/worker.o controller/worker.cpp

compile/save_db.o: model/save_db.cpp model/save_db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/save_db.o model/save_db.cpp

compile/init_mysql.o: model/init_mysql.cpp model/init_mysql.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/init_mysql.o model/init_mysql.cpp

compile/moc_util_skyw.o: compile/moc_util_skyw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/moc_util_skyw.o compile/moc_util_skyw.cpp

compile/moc_skywavenetwork.o: compile/moc_skywavenetwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/moc_skywavenetwork.o compile/moc_skywavenetwork.cpp

compile/moc_worker.o: compile/moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile/moc_worker.o compile/moc_worker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

